main: me.bobomcc.main
name: BoboMCC
version: '2.1'
description: Minecraft Hunger Games Style GameMode
load: POSTWORLD
author: BoboHleach
commands:
  class:
    description: Selects Class
    usage: /<command>
  start:
    description: Starts the game
    usage: /<command>
  team:
    description: Sets team for users
    usage: /<command> [team_name]